### PR TITLE
Add dari language code

### PR DESCRIPTION
**Pull request by StianHaugland1**

### CODE REVIEW

**Review by benq66 — APPROVED** [review]
lgtm

**Review by Gutodotado24 — APPROVED** [review]

**Comment by brettz9** [comment]
FWIW, in the course of reviewing [intl-locale-textinfo-polyfill](https://github.com/brettz9/intl-locale-textinfo-polyfill), I created this detection script to see what codes Chrome recognized:

```js
const aCode = 'a'.charCodeAt();
const zCode = 'z'.charCodeAt();

const codes = [];
for (let i = aCode; i <= zCode; i++) {
  for (let j = aCode; j <= zCode; j++) {
    try {
      const code = String.fromCharCode(i) +
        String.fromCharCode(j);
      const dir = new Intl.Locale(
        code
      ).textInfo.direction;
      if (dir === 'rtl') {
        codes.push(code);
      }
      else if (dir !== 'ltr') {
        console.error('dir', dir);
        throw new Error('What?');
      }
    }
    catch (err) {
    }
    for (let k = aCode; k <= zCode; k++) {
      try {
        const code = String.fromCharCode(i) +
          String.fromCharCode(j) +
          String.fromCharCode(k);
        const dir = new Intl.Locale(
          code
        ).textInfo.direction;
        if (dir === 'rtl') {
          codes.push(code);
        }
        else if (dir !== 'ltr') {
          console.error('dir', dir);
          throw new Error('What?');
        }
      }
      catch (err) {
      }
    }
  }
}
console.log('codes', codes);
```

...and I found the following codes were missing (and they seemed to make sense to be added to rtl-detect):

    'ara', 'arb', 'drw', 'fas', 'heb', 'iw', 'pbu', 'per', 'pes', 'pus', 'tnf', 'urd'

And puzzlingly, I found the following codes were *not* rtl according to Chrome's implementation (and which I've reported at https://bugs.chromium.org/p/chromium/issues/detail?id=1404390 ):

    ae, arc, bcc, bqi, dv, glk, ku, mzn, nqo, pnb, sd, ug, yi

**Comment by asakusuma** [comment]
I've created a fork here that uses the `Intl` API when possible: 
https://github.com/asakusuma/rtl-detect-intl
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/getTextInfo

**Review by shadiabuhilal — APPROVED** [review]
👍

**Comment by shadiabuhilal** [comment]
Looks good 
https://en.wikipedia.org/wiki/Dari

**Pull request merged**
